CREATE TABLE IF NOT EXISTS ${db}.${table} (

    airline_iata_code STRING,
    airline_name STRING,
    year_month STRING COMMENT "Format yyyyMM",
    flight_number INT,
    scheduled_departure TIMESTAMP,
    effective_departure TIMESTAMP,
    departure_delay INT,
    departure_delay_weight DOUBLE,
    total_departure_delay BIGINT,
    scheduled_arrival TIMESTAMP,
    effective_arrival TIMESTAMP,
    arrival_delay INT,
    arrival_delay_weight DOUBLE,
    total_arrival_delay BIGINT,
    air_system_delay INT,
    air_system_delay_weight DOUBLE,
    total_air_system_delay BIGINT,
    security_delay INT,
    security_delay_weight DOUBLE,
    total_security_delay BIGINT,
    airline_delay INT,
    airline_delay_weight DOUBLE,
    total_airline_delay BIGINT,
    late_aircraft_delay INT,
    late_aircraft_delay_weight DOUBLE,
    total_late_aircraft_delay BIGINT,
    weather_delay INT,
    weather_delay_weight DOUBLE,
    total_weather_delay BIGINT,
    delay_unit_measure STRING,
    number_of_delayed_flights BIGINT,
    param_start_date STRING COMMENT "Pig job parameter: $startDate",
    param_end_date STRING COMMENT "Pig job parameter: $endDate",
    param_airline_iatas STRING COMMENT "Pig job parameter: $airlineIatas",
    requesting_user STRING COMMENT "User that issued the data request",
    workflow_job_id STRING COMMENT "Oozie workflow job id",
    job_type STRING COMMENT "Job type (PIG|HIVE|SPARK)",
    ts_insert TIMESTAMP COMMENT "Data insert timestamp",
    dt_insert STRING COMMENT "Data insert date"
)
STORED AS PARQUET;

TRUNCATE TABLE ${db}.${table};