spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_request_lgd?currentSchema=oozie
    username: cloudera
    password: cloudera
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

oozie:
  url: http://quickstart.cloudera:11000/oozie