spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_request_lgd
    username: cloudera
    password: cloudera
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

oozie:
  url: http://quickstart.cloudera:11000/oozie