spring:
  datasource:
    url: @jdbc.url@
    username: cloudera
    password: cloudera
    driverClassName: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    baselineVersion: 0

oozie:
  url: http://quickstart.cloudera:11000/oozie